//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Monopoly.
        /// </summary>
        public static string AddEnhancementMenuItemHeader {
            get {
                return ResourceManager.GetString("AddEnhancementMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/robinschiro/MonopolyDeal/releases/latest/download/AutoUpdaterManifest.xml.
        /// </summary>
        public static string AutoUpdaterManifestUrl {
            get {
                return ResourceManager.GetString("AutoUpdaterManifestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string DefaultVolume {
            get {
                return ResourceManager.GetString("DefaultVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DiscardMenuItemHeader {
            get {
                return ResourceManager.GetString("DiscardMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Card.
        /// </summary>
        public static string FlipCardMenuItemHeader {
            get {
                return ResourceManager.GetString("FlipCardMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bit.ly/2lQWlcq.
        /// </summary>
        public static string GiveFeedbackUrl {
            get {
                return ResourceManager.GetString("GiveFeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string PleaseWaitWindowTitle {
            get {
                return ResourceManager.GetString("PleaseWaitWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://monopolydealrules.com/.
        /// </summary>
        public static string RulesUrl {
            get {
                return ResourceManager.GetString("RulesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate Wild Card.
        /// </summary>
        public static string SeparateWildCardMenuItemHeader {
            get {
                return ResourceManager.GetString("SeparateWildCardMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ServerIpAddress.
        /// </summary>
        public static string SettingIpAddressKey {
            get {
                return ResourceManager.GetString("SettingIpAddressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -PlayerName.
        /// </summary>
        public static string SettingNameKey {
            get {
                return ResourceManager.GetString("SettingNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14242.
        /// </summary>
        public static string SettingPortDefaultValue {
            get {
                return ResourceManager.GetString("SettingPortDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Port.
        /// </summary>
        public static string SettingPortKey {
            get {
                return ResourceManager.GetString("SettingPortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonopolyDeal\MonopolyDealSettings.txt.
        /// </summary>
        public static string SettingsFilePath {
            get {
                return ResourceManager.GetString("SettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string SettingSoundEffectsEnabledDefaultValue {
            get {
                return ResourceManager.GetString("SettingSoundEffectsEnabledDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -SoundEffectsEnabled.
        /// </summary>
        public static string SettingSoundEffectsEnabledKey {
            get {
                return ResourceManager.GetString("SettingSoundEffectsEnabledKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string SettingTurnNotificationDialogEnabledDefaultValue {
            get {
                return ResourceManager.GetString("SettingTurnNotificationDialogEnabledDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -TurnNotificationDialogEnabled.
        /// </summary>
        public static string SettingTurnNotificationDialogEnabledKey {
            get {
                return ResourceManager.GetString("SettingTurnNotificationDialogEnabledKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/GameObjects;component/Audio/ActionDing.wav.
        /// </summary>
        public static string UriPathActionDing {
            get {
                return ResourceManager.GetString("UriPathActionDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/GameObjects;component/Audio/MoneyDing.wav.
        /// </summary>
        public static string UriPathMoneyDing {
            get {
                return ResourceManager.GetString("UriPathMoneyDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/GameObjects;component/Audio/Silence.wav.
        /// </summary>
        public static string UriPathSilence {
            get {
                return ResourceManager.GetString("UriPathSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/GameObjects;component/Audio/TurnDing.wav.
        /// </summary>
        public static string UriPathTurnDing {
            get {
                return ResourceManager.GetString("UriPathTurnDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/GameObjects;component/Audio/WinningMusic.wav.
        /// </summary>
        public static string UriPathWinningMusic {
            get {
                return ResourceManager.GetString("UriPathWinningMusic", resourceCulture);
            }
        }
    }
}
